name = "Split-Screen Mod"
description = "Adds support for 4-player split-screen to the game"

[preload]
packages = [
    # Skeletons
    "PDLCIN_B3_Anim2",
]
keep_alive = [
    # Skeletons
    "Skeletons.Mesh.Batman_Skeleton_Skin",
]

[options]
layout_horizontal = false
players = [
    [
        "Playable_RobinStoryDLC",
        "Std",
    ],
    [
        "Playable_Catwoman",
        "Std",
    ],
    [
        "Playable_Nightwing",
        "Std",
    ],
]
